### ISSUE TITLE
Can't install this with TYPO3 11.5.2

### ISSUE THREAD

**Issue by PhilippKuhlmay** [helhum/typo3-deployer-recipe#11]
TYPO3 11.3.1 requires `symfony/yaml: ^5.3.0,` but this requires `symfony/yaml": "^3.0 || ^4.0"`. So i can't install this one with TYPO3 11.5.x

<pre>
    - Root composer.json requires helhum/typo3-deployer-recipe dev-master -> satisfiable by helhum/typo3-deployer-recipe[dev-master].
    - You can only install one version of a package, so only one of these can be installed: symfony/yaml[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.29, v5.0.0, ..., v5.3.6].
    - Conclusion: install symfony/yaml v5.3.0 (conflict analysis result)
    - Root composer.json requires typo3/cms-core ^11.5 -> satisfiable by typo3/cms-core[v11.5.0, v11.5.1, v11.5.2].
    - Conclusion: don't install symfony/yaml[v5.3.0] | install one of symfony/yaml[v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.3.11] (conflict analysis result)
</pre>

**Comment by helhum** [comment]
See: https://github.com/helhum/typo3-deployer-recipe/issues/8#issuecomment-959312788
