### ISSUE TITLE
Release status

### ISSUE THREAD

**Issue by featdd** [helhum/typo3-deployer-recipe#8]
Hi @helhum,

is the status still beta or do you mind giving it a version tag for composer require?
Requiring dev-master is kind of a bad thing 😄 

Greetings
Daniel

**Comment by Navi2016** [comment]
Yea that would be great. But is still still being supported at all?

**Comment by helhum** [comment]
It is an opinionated recipe for how I personally do my TYPO3 deployments. It is meant for my my personal use only and not supported at all in terms of something that I release, advertise or maintain in any way.

In that sense publishing it on Packagist was a mistake and I abandoned it there now, making it clear, that this will never be maintained at all.

The only reason I made this public is to give inspiration how it could work. So my advice is:

Fork it and use the fork the way you like it to
