### ISSUE TITLE
Not possible to pass options to "runConsole" 

### ISSUE THREAD

**Issue by theLine** [helhum/typo3-deployer-recipe#9]
With Deployer it's possible to pass options to the `run` function, as you can see here https://deployer.org/docs/api.html#run.

Unfortunately your `runConsole` function is lacking this argument.

By default Deployer's timeout for commands is 300 seconds.
But commands like `language:update` may take much longer than this and will be terminated.

I'd be nice to add the `$option` argument to your `runConsole` function.
See PR #10

**Comment by helhum** [comment]
See: https://github.com/helhum/typo3-deployer-recipe/issues/8#issuecomment-959312788
